### ISSUE TITLE
Implement px:epub3-enhance

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#406]
This would be a step that takes a EPUB3 fileset as input and then performs a series of operations that enhances the EPUB in terms of semantic markup and best practices.

The step might be exposed as a script as well, but is mainly for post-processing epubs in other scripts.
- [ ] List tables in navigation document #402 
- [ ] List illustrations in navigation document #403 
- [ ] Make HTML outline explicit #404 
- [ ] Change HTML outline according to best practices #405 

Use the epub3-enhance step in the following scripts:
- [ ] daisy202-to-epub3
- [ ] zedai-to-epub3
- [ ] dtbook-to-epub3
- [ ] html-to-epub3
- [ ] daisy3-to-epub3

**Comment by bertfrees** [comment]
Note that there is now also a epub3-to-epub3 script.
